columns:
  customerID: str
  gender: str
  SeniorCitizen: int
  Partner: str
  Dependents: str
  tenure: int
  PhoneService: str
  MultipleLines: str
  InternetService: str
  OnlineSecurity: str
  OnlineBackup: str
  DeviceProtection: str
  TechSupport: str
  StreamingTV: str
  StreamingMovies: str
  Contract: str
  PaperlessBilling: str
  PaymentMethod: str
  MonthlyCharges: float
  TotalCharges: float
  Churn: str

drop_columns: _id

dataset_schema:
  target_column: Churn
  id_column: customerID

numeric_columns:
  - SeniorCitizen
  - tenure
  - MonthlyCharges
  - TotalCharges

categorical_columns:
  - gender
  - Partner
  - Dependents
  - PhoneService
  - MultipleLines
  - InternetService
  - OnlineSecurity
  - OnlineBackup
  - DeviceProtection
  - TechSupport
  - StreamingTV
  - StreamingMovies
  - Contract
  - PaperlessBilling
  - PaymentMethod
  - Churn

domain_values:
  gender: ["Male", "Female"]
  SeniorCitizen: [0, 1]
  Partner: ["Yes", "No"]
  Dependents: ["Yes", "No"]
  PhoneService: ["Yes", "No"]
  MultipleLines: ["Yes", "No", "No phone service"]
  InternetService: ["DSL", "Fiber optic", "No"]
  OnlineSecurity: ["Yes", "No", "No internet service"]
  OnlineBackup: ["Yes", "No", "No internet service"]
  DeviceProtection: ["Yes", "No", "No internet service"]
  TechSupport: ["Yes", "No", "No internet service"]
  StreamingTV: ["Yes", "No", "No internet service"]
  StreamingMovies: ["Yes", "No", "No internet service"]
  Contract: ["Month-to-month", "One year", "Two year"]
  PaperlessBilling: ["Yes", "No"]
  PaymentMethod:
    - Electronic check
    - Mailed check
    - Bank transfer (automatic)
    - Credit card (automatic)
  Churn: ["Yes", "No"]

mongodb:
  database: Proj3
  collection: Proj3-Data
  id_field: customerID
